[alias]
xtask = "run --package xtask --"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-Clink-arg=-Tplatform/riscv64-virt/linker.ld"]
